### ISSUE TITLE
Tag logic

### ISSUE THREAD

**Issue by apeck12** [lcls-users/btx#133]
I'm starting to think we could define an overall `setup.tag` and maybe have the option to overwrite it with `task.tag`?

_Originally posted by @fredericpoitevin in https://github.com/lcls-users/btx/pull/132#discussion_r877593792_

**Comment by fredericpoitevin** [comment]
After discussion, we set a strict rule of only having `setup.tag` and never `task.tag`.

So, `setup` now encompasses all shared parameters for a workflow and `tasks` things that are more task specific.

```yaml
setup:
  root_dir:
  exp:
  run:              <--- make sure that it can be a range
  tag:
```
And the `detector` would move to the tasks that need to have it specified.

For event code business, we would rely on smalldata once it is integrated as a task, e.g.:
```yaml
smd:
  xray_evt:
  laser_evt:
```
