### ISSUE TITLE
Analysis - Progress

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#197]
09/13/20: data moved back on FFB nodes.

# Setup

## "install" `btx`

add the following line in your `~/.bashrc`:
```bash
export PATH=/cds/sw/package/autosfx/btx/scripts:$PATH
```
and prepare the working directory (**It if exists already, please change the directory name to avoid overwriting this one**)
```bash
ssh psffb
cd /cds/data/drpsrcf/mfx/mfxx49820/scratch
mkdir btx
```
## prepare input files
Create a sub-directory specifically for storing the .yaml files, e.g.:
```bash
cd btx
mkdir yamls
```
Here is the initial `mfxx49820.yaml` file:
```yaml
setup:
  queue: 'anaq'
  root_dir: '/cds/data/drpsrcf/mfx/mfxx49820/scratch/btx'
  exp: 'mfxx49820'
  run: 8
  det_type: 'epix10k2M'
  cell: '/cds/data/drpsrcf/mfx/mfxx49820/scratch/btx/cell/reference.cell'

fetch_mask:
  dataset: '/data/data'

fetch_geom:

build_mask:
  thresholds: -10 5000
  n_images: 20
  n_edge: 1
  combine: True

run_analysis:
  max_events: -1

opt_geom:
  n_iterations: 5
  n_peaks: 3
  threshold: 1000000

find_peaks:
  tag: ''
  psana_mask: False
  min_peaks: 10
  max_peaks: 2048
  npix_min: 2
  npix_max: 30
  amax_thr: 40.
  atot_thr: 180.
  son_min: 10.0
  peak_rank: 3
  r0: 3.0
  dr: 2.0
  nsigm: 10.0

index:
  time: '1:30:00'
  ncores: 64
  tag: 'sample1'
  int_radius: '3,4,5'
  methods: 'mosflm,xds'
  tolerance: '5,5,5,1.5'
  no_revalidate: True
  multi: True
  profile: True
  cell: '/cds/data/drpsrcf/mfx/mfxx49820/scratch/btx/cell/reference.cell'

stream_analysis:
  tag: 'sample1'

merge:
  tag: 'sample1'
  symmetry: '4/mmm_uac'
  iterations: 1
  model: 'unity'
  foms: 'CCstar Rsplit'
  nshells: 10
  highres: 2.5

solve:
  tag: 'sample1'
  pdb: '/cds/data/drpsrcf/mfx/mfxx49820/scratch/btx/cell/193l.pdb'

refine_center:
  runs: 9 14
  dx: -1 1 3
  dy: -1 1 3

refine_distance:
  runs: 9 14 1
  dz: -0.002 0.002 5
```
Note that it expects a `reference.cell` and `193l.pdb` files in `btx/cell/`, corresponding to reference lysozyme crystal information. Here is the reference cell file:
```
CrystFEL unit cell file version 1.0
lattice_type = tetragonal
unique_axis = c
a = 78.540 A
b = 78.540 A
c = 37.770 A
al = 90 deg
be = 90 deg
ga = 90 deg
```

## launchpad
We like to launch all jobs from `btx/launchpad/`.

All set!

# Process

## metrology setup and optimization
```bash
elog_submit.sh -c ../yamls/mfxx49820.yaml -t fetch_geom -n 1
elog_submit.sh -c ../yamls/mfxx49820.yaml -t fetch_mask -n 1
```
We use the silver behenate run 8 to roughly optimize the geometry.
```
elog_submit.sh -c ../yamls/mfxx49820.yaml -t run_analysis -n 48 -r 8
elog_submit.sh -c ../yamls/mfxx49820.yaml -t opt_geom -n 1 -r 8  
```
Upon inspection of the output `/cds/data/drpsrcf/mfx/mfxx49820/scratch/btx/geom/figs/r0008.png'`, we're not super happy about the centering:
```
New center is (831.1198456445635, 833.0406750639429)
Detector distance inferred from powder rings: 279.6 mm
```
 - even though the rings seem to roughly be of the right size:
![image](https://user-images.githubusercontent.com/4610338/190046177-6d40663a-d25a-4c8a-8fdd-aba3463c9534.png)
By initializing the center search to:
```yaml
opt_geom:
  n_iterations: 5
  n_peaks: 3
  threshold: 1000000
  center: 843 833
```
we get:
```
New center is (843.5532519182825, 831.0710902924419)
Detector distance inferred from powder rings: 280.47 mm
```
and a better result:
![image](https://user-images.githubusercontent.com/4610338/190047411-7e5ce81d-10db-46ed-a488-17f42a2db568.png)

Just for kicks, let's update the mask now:
```
elog_submit.sh -c ../yamls/mfxx49820.yaml -t build_mask -n 1 -r 8
```

#### Initial geometry

```bash
submit_range_run.sh -c ../yamls/mfxx49820.yaml -t find_peaks -n 48 -r 9 -s 14
submit_range_run.sh -c ../yamls/mfxx49820.yaml -t index -q anaq -r 9 -s 14
```
The amount of indexed patterns was: zero.

#### Geometry refinement

With the following settings, we will first refine the detector center (four pixels in each direction by steps of two pixels):
```
refine_center:
  runs: 11 12
  dx: -4 4 5
  dy: -4 4 5
```
```bash
elog_submit.sh -c ../yamls/mfxx49820.yaml -t refine_center -q anaq
```
to no avail... Let's scan the distance (9mm in each direction in steps of 3mm)
```
refine_distance:
  runs: 11 14 1
  dz: -0.009 0.009 5
```
That did not help either. Let's move on

### sample 2 - runs 15 to 33
changed `tag` to `sample2` in the .yaml
```bash
submit_range_run.sh -c ../yamls/mfxx49820.yaml -t find_peaks -q anaq -n 48 -r 15 -s 33
submit_range_run.sh -c ../yamls/mfxx49820.yaml -t index -q anaq -r 15 -s 33
```
This time we get 1679 indexed, even though we forgot to update the geometry after a detector move in run 15. Let's fix that now:
```bash
elog_submit.sh -c ../yamls/mfxx49820.yaml -t run_analysis -n 48 -r 15
elog_submit.sh -c ../yamls/mfxx49820.yaml -t opt_geom -n 1 -r 15
```
It appears that the center was way off again:
```
New center is (841.1970230601174, 834.0060622898853)
Detector distance inferred from powder rings: 49.58 mm
```
![image](https://user-images.githubusercontent.com/4610338/190279181-72cc64c1-30d4-43d8-a035-2baed10cf07a.png)
Looks like moving in the opposite direction might help, let's try:
```yaml
```yaml
opt_geom:
  n_iterations: 5
  n_peaks: 3
  threshold: 1000000
  center: 823 833
```
Much better - although given the big change in center and distance it is surprising that we were able to index anything above!
```
New center is (825.0562345967105, 835.9737619465618)
Detector distance inferred from powder rings: 102.68 mm
```
![image](https://user-images.githubusercontent.com/4610338/190279610-0fd8b4ca-c4ae-4ec3-a1fb-f91d9e839b7e.png)
Let's further refine the center now:
```yaml
refine_center:
  runs: 16 33
  dx: -1 1 3
  dy: -1 1 3
```
```bash
elog_submit.sh -c ../yamls/mfxx49820.yaml -t refine_center -q anaq
```
The "number of indexed" metric shows a clear trend
![image](https://user-images.githubusercontent.com/4610338/190453869-2694237f-08cd-4be5-8f43-58fc3d80185a.png)
that is not exactly followed by the "Rsplit" metric that we use to automatically update the geometry - but at least we updated in the right direction.
![image](https://user-images.githubusercontent.com/4610338/190454103-de18c0e1-8af2-4d3c-9af9-0c74140bee89.png)
Let's refine the distance now:
```yaml
refine_distance:
  runs: 16 33 1
  dz: -0.002 0.002 5
```
Looks like the silver behenate data was spot on:
![image](https://user-images.githubusercontent.com/4610338/190455216-ad7d3d12-8250-4053-8da0-fac65588c7d4.png)
![image](https://user-images.githubusercontent.com/4610338/190455274-f127d622-5ae2-4e17-9b97-a73a80f883ea.png)
Let's try to further refine the center:
```yaml
refine_center:
  runs: 16 33
  dx: 0 2 3
  dy: -2 0 3
```
The result tends to suggest that we should push down on `y` a bit more, even though that hurts the total number of indexed:
![image](https://user-images.githubusercontent.com/4610338/190479818-972d929e-23a3-4551-9b84-9de6c45ace0e.png)
![image](https://user-images.githubusercontent.com/4610338/190479841-a6918cdc-80ea-4bc5-9789-f189c8ad78fc.png)
Let's do that:
```yaml
refine_center:
  runs: 16 33
  dx: -1 1 3
  dy: -2 0 3
```
We have converged:
![image](https://user-images.githubusercontent.com/4610338/190500733-1be2344a-0d76-49ca-8ab1-3352472fe15a.png)
![image](https://user-images.githubusercontent.com/4610338/190500714-d966bda2-d5c6-4bf5-b0ee-5fb791d58076.png)
In summary, the final center is 1 pixel in +x and 3 in -y compared to what the silver behenate run provided.
A final check on the distance:
```yaml
refine_distance:
  runs: 16 33 1
  dz: -0.001 0.001 5
```
The optimal distance was moved by half a mm which might not be statistically justified. We'll go with this geometry going forward:
![image](https://user-images.githubusercontent.com/4610338/190514055-aa80d24d-6f3e-4370-a2df-6fcb84b904e2.png)
Let's index again, this time adding xgandalf and starting from the refined cell file:
```yaml
index:
  time: '1:30:00'
  ncores: 64
  tag: 'sample2'
  int_radius: '3,4,5'
  methods: 'mosflm,xds,xgandalf'
  tolerance: '5,5,5,1.5'
  no_revalidate: True
  multi: True
  profile: True
  cell: '/cds/data/drpsrcf/mfx/mfxx49820/scratch/btx/cell/sample2.cell'
```
```bash
rm ../index/r00*sample2.stream
submit_range_run.sh -c ../yamls/mfxx49820.yaml -t index -q anaq -r 16 -s 33
```
We had so many indexed that we ran into a new problem: #199 
`cat`-ing the stream files manually allowed us to carry on to the merging step. Rsplit and CC* look good at least up to 1.8A
![image](https://user-images.githubusercontent.com/4610338/190568638-86303f22-c520-40b6-998c-8db6bd4d5a40.png)
![image](https://user-images.githubusercontent.com/4610338/190568683-b7585d48-fa1f-4f1a-b401-622444ca656a.png)
Overall, with 89,294 indexed on the second shift, we got:
- resolution: 1.8A
- Rsplit=10.4%
- CC*=0.99 
- R / Rfree = 0.18/0.21

![image](https://user-images.githubusercontent.com/4610338/190574853-12ea7367-8fac-4703-903b-8bebeb6046a2.png)
![image](https://user-images.githubusercontent.com/4610338/190576019-56ce5d36-438d-4ae1-b473-b2f9e6db3363.png)
![image](https://user-images.githubusercontent.com/4610338/190569425-02b56317-786d-4c51-b88e-c9d2b8671784.png)

#### Geometry check

Silver behenate was collected at runs 34 and 42 but the eLog says the detector and samples were never moved. Let's quickly check if there is any drift.

```bash
elog_submit.sh -c ../yamls/mfxx49820.yaml -t run_analysis -n 48 -r 34
elog_submit.sh -c ../yamls/mfxx49820.yaml -t opt_geom -n 1 -r 34
elog_submit.sh -c ../yamls/mfxx49820.yaml -t run_analysis -n 48 -r 42
elog_submit.sh -c ../yamls/mfxx49820.yaml -t opt_geom -n 1 -r 42
```
Run 34 looks unchanged with a good powder fit:
```
New center is (825.9308140544783, 836.9225054631489)
Detector distance inferred from powder rings: 102.16 mm
```
![image](https://user-images.githubusercontent.com/4610338/190677078-0d49be46-0af2-4307-aa4a-9ac5593efaad.png)
so let's keep the geometry refined before up to run 41.
```bash
submit_range_run.sh -c ../yamls/mfxx49820.yaml -t find_peaks -q anaq -n 48 -r 35 -s 123
submit_range_run.sh -c ../yamls/mfxx49820.yaml -t index -q anaq -r 35 -s 41
```
No hits found.

Silver behenate analysis at run 42 looks bad:
```
New center is (825.8134421891697, 836.8234436738529)
Detector distance inferred from powder rings: 185.14 mm
```
![image](https://user-images.githubusercontent.com/4610338/190683568-fa3341e4-e412-4eba-a7dc-766d231d7070.png)
It was picking up on the speck of dust at low-q. Increasing the number of observed rings to fit did the trick:
```yaml
opt_geom:
  n_iterations: 5
  n_peaks: 6
  threshold: 1000000
  center: 823 833
```
```
New center is (825.794742527854, 836.8193397426567)
Detector distance inferred from powder rings: 102.05 mm
```
![image](https://user-images.githubusercontent.com/4610338/190685978-6b485133-f195-4789-af27-5526f772d11c.png)
Overall it looks like the geometry did not move much from what we refined above so we will keep what we had.
```bash
submit_range_run.sh -c ../yamls/mfxx49820.yaml -t index -q anaq -r 43 -s 123
```
![image](https://user-images.githubusercontent.com/4610338/190728713-36a5c78e-a431-499a-86a8-1e7b68a09aa7.png)
![image](https://user-images.githubusercontent.com/4610338/190728740-80a0e9fc-fb59-400a-afc5-88db2ca4a5ec.png)

Keeping in mind that the resolution at the edge of the detector is roughly 1.9A, we get the following stats for the whole experiment:
- number of indexed: 145,359
- resolution: 1.6A
- Rsplit=8.7%
- CC*=0.99 
- R / Rfree = 0.21/0.24 
![image](https://user-images.githubusercontent.com/4610338/190730048-510000e9-4641-4abd-a959-b1a0c92d5a2e.png)
![image](https://user-images.githubusercontent.com/4610338/190730064-a1daad2a-ce73-42af-b7e3-bd0169f6ff96.png)
![image](https://user-images.githubusercontent.com/4610338/190729837-3c6bc75f-1be7-4b09-8b10-b155dfb6c301.png)
