### ISSUE TITLE
Run diagnostics: tracking beam and photon energies and other statistics

### ISSUE THREAD

**Issue by apeck12** [lcls-users/btx#273]
The `run_analysis` task tracks the beam and photon energies along with other statistics across a run. Currently diagnostic visuals like the ones below are output:
![stats_r0019](https://user-images.githubusercontent.com/6363287/219877616-63e6dc53-114d-48cd-a497-51c03d33bb16.png)
![stats_energy_r0019](https://user-images.githubusercontent.com/6363287/219877619-3b3d5c9f-ca69-4857-9999-fed9b7dbe24b.png)

The above images can be generated as follows. First, add the following line to your `~/.bashrc`:
```export PATH=/cds/sw/package/autosfx/btx/scripts:$PATH```

Then, in the experiment’s scratch folder, create a new directory `btx` with subdirectories `launchpad` and `yamls`:
```
ssh psana
mkdir /cds/data/psdm/mfx/mfxp23120/scratch/btx && cd $_
mkdir launchpad yamls
```

In the `yamls` folder, use a text editor to create test.yaml, a minimal configuration file that contains the following:
```
setup:
  queue: 'psanaq'
  root_dir: '/cds/data/psdm/mfx/mfxp23120/scratch/btx’
  exp: 'mfxp23120'
  run: 19
  det_type: 'epix10k2M'

build_mask:
  thresholds: -200 50000
  n_images: 20
  n_edge: 1
  combine: False

run_analysis:
  ncores: 8
  outlier_threshold: 50
```

Then from the `launchpad` directory, we first generate a mask since the `run_analysis` task requires one.
```elog_submit.sh -c ../yamls/test.yaml -t build_mask -n 1 -f SLAC -q psanaq```
The masked pixels will include the edge pixels of each detector panel and any pixels from a random selection of 20 images whose intensities lie outside the thresholds specified in the yaml.

We can then submit the `run_analysis` to the task for a particular run (the `-r` flag) as follows:
```elog_submit.sh -c ../yamls/test.yaml -t run_analysis -r 19 -f SLAC -q psanaq```

The results can be found in this folder: 
```/cds/data/psdm/mfx/mfxp23120/scratch/btx/powder```
where the subdirectory figs contains figures like the ones shown above. The traces are saved as numpy arrays, with nomenclature `r00XX_trace_{statistic}.npy`. 

We'd welcome any feedback on additional diagnostics that would be useful during the experiment or for downstream analysis.
