### ISSUE TITLE
`update_mask` DAG

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#67]
We list the tasks that define each DAG. We consider a task completed when successfully ran manually on the FFB nodes, and a DAG completed when successfully ran through the eLog. 

- [x] `build_mask`: #72 
```bash
$ . elog_submit.sh -c ../tutorial/mfxlv4920.yaml -t build_mask -n 1
```
```yaml
build_mask:
  thresholds: -10 2000
  n_images: 10
  n_edge: 2
  combine: True
```
pulls a collection of random images from the run and masks pixels whose intensities fall outside the user-defined threshold values. This mask can be combined with a previous mask, and a set width of border pixels can be masked as well depending on the config task arguments.

- [ ] `report`

- [ ] `display`
